export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const CHECK_LOCAL_STORAGE_IF_LOGGED_IN = 'CHECK_LOCAL_STORAGE_IF_LOGGED_IN';


export const SEARCH_FLIGHT_CLICKED = 'SEARCH_FLIGHT_CLICKED';
export const FLIGHT_SELECT_CLICKED = 'FLIGHT_SELECT_CLICKED';
export const SEAT_SELECTED = 'SEAT_SELECTED';
export const SEAT_UNSELECTED = 'SEAT_UNSELECTED';
